#!/usr/bin/env python

import json, time, threading
import rospy
import ttk
from Tkinter import *

from std_msgs.msg import String
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry


'''
Test

'''
class Test:

    def __init__(self, pub):

        # Array to hold steps of linear and angular vel
        self.__steps = []

        # Velocity to publish
        self.__twist = Twist()

        # Control's publisher
        self.publisher = pub

 
    def add_step(self, step):
        self.__steps.append(step)


    def start(self):
        for step in self.__steps:
            self.__twist.linear.x  = step[0]
            self.__twist.angular.z = step[1]
            self.publisher.publish(self.__twist)
            time.sleep(step[2])



'''
Controls

'''
class Controls:

    def __init__(self, master):
        
        # May be removed unless otherwise found useful
        self.count = 0

        # Ros publisher for velocity message
        self.publisher = rospy.Publisher('/cmd_vel', Twist, queue_size=10)

        self.current_linear  = 0.0
        self.current_angular = 0.0

        # Main window frame
        self.master = master

        master.title("Terrapin Controls")

        content  = ttk.Frame(master, padding="5 5 5 5")
        content.grid(column=0, row=0)

        # Text area for console output
        self.messages = Text(content, width=65, height=30, state="disabled")
        self.messages.grid(column=3, row=0)

        # Frame to hold arrow controls
        btnFrame = ttk.Frame(content, borderwidth=2,
                relief="solid", padding="7 7 7 7")
        btnFrame.grid(column=0, row=0, columnspan=3, rowspan=2)

        # Increase linear velocity button
        self.up_button = ttk.Button(btnFrame, text="Up",
                command=self.__up_btn_cb)
        self.up_button.grid(column=2, row=0,
                columnspan=1)

        # Decrease linear velocity button
        self.dn_button = ttk.Button(btnFrame, text="Down",
                command=self.__dn_btn_cb)
        self.dn_button.grid(column=2, row=1,
                columnspan=1)

        # Increase angular velocity button
        self.lt_button = ttk.Button(btnFrame, text="Left",
                command=self.__lt_btn_cb)
        self.lt_button.grid(column=1, row=1)

        # Decrease angular velocity button
        self.rt_button = ttk.Button(btnFrame, text="Right",
                command=self.__rt_btn_cb)
        self.rt_button.grid(column=3, row=1)

        # Create tests and test frame
        self.test_1 = Test(self.publisher)
        self.test_1.add_step([-0.2,  0.0, 5])
        self.test_1.add_step([-0.2,  0.4, 5])
        self.test_1.add_step([-0.2, -0.4, 5])


        testFrame = ttk.Frame(content, padding="7 7 7 7")
        testFrame.grid(column=0, row=1, columnspan=3, rowspan=1)

        self.test_btn_1 = ttk.Button(testFrame, text="Test 1", command=self.__test_cb_1)
        self.test_btn_1.grid(column=0, row=0)


    def __up_btn_cb(self):
        self.current_linear += 0.1
        self.publisher.publish(self.__twist())


    def __dn_btn_cb(self):
        self.current_linear -= 0.1
        self.publisher.publish(self.__twist())


    def __lt_btn_cb(self):
        self.current_angular += 0.1
        self.publisher.publish(self.__twist())


    def __rt_btn_cb(self):
        self.current_angular -= 0.1
        self.publisher.publish(self.__twist())


    def __run_test(self):
        self.test_1.start()


    def __test_cb_1(self):
        threading.Thread(target=self.__run_test).start()


    def __twist(self):
        twist = Twist()
        twist.linear.x  = self.current_linear
        twist.angular.z = self.current_angular
        return twist

    
    def __sub_cb(self, dat):
        # velocity
        # displacement
        # deltaT
        # deltaX
        # deltaY
        # deltaZ
        # previousCloudNum
        # previousTimestamp
        # previousNumKeypoints
        # currentCloudNum
        # currentTimestamp
        # ---------------------
        # currentNumKeypoints |

        print("sub called\n")
        self.count += 1


        # Wait for an odom message to be published
        odom     = rospy.wait_for_message('/odom', Odometry)
        odom_vel = odom.twist.twist.linear.x

        dat_dict = json.loads(dat.data)
        dat_dict['odom velocity'] = odom_vel

        str_msg = ''
        str_msg += 'frame ' + str(self.count) + '\n'
        str_msg += '-----\n'
        max_x   = 21
        val     = None
        for key in dat_dict:
            key = str(key)
            val = str(dat_dict[key])
            num_spaces_key = max_x - len(key)
            num_spaces_val = max_x - len(val)

            for i in range(0, num_spaces_key):
                str_msg += ' '

            str_msg += key + ':'

            for i in range(0, num_spaces_val):
                str_msg += ' '

            str_msg += val + '\n\n'


        # Enable for writing and deleting
        self.messages['state'] = 'normal'

        # Insert new message
        self.messages.delete('1.0', 'end')
        self.messages.insert('1.0', str_msg)

        # No longer want input
        self.messages['state'] = 'disabled'


    def startup(self):
        rospy.init_node('terrapin_controller', anonymous=True)

        # Subscribe to test message
        rospy.Subscriber('/terrapin/json_message', String, self.__sub_cb)

        self.master.mainloop()





if __name__ == '__main__':
    # Pass in root tk element
    controls = Controls( Tk() )

    controls.startup()

